image:
  repository: freshrss/freshrss
  tag: "1.28.1"
  type: alpine
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.205"

ingress:
  enabled: false

freshrss:
  baseUrl: "http://freshrss.verticon.com"
  timezone: "America/New_York"
  environment: production
  cronjob:
    type: internal
    minutes: "1,31"
  database:
    type: postgresql
  initialization:
    enabled: false
    admin:
      username: admin
      email: "jconlon@verticon.com"
    apiEnabled: true
    language: en
  persistence:
    enabled: true
    data:
      enabled: true
      storageClass: rook-ceph-block
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    extensions:
      enabled: true
      storageClass: rook-ceph-block
      size: 1Gi
      accessModes:
        - ReadWriteOnce

externalPostgresql:
  auth:
    database: "freshrss"
    username: "freshrss"
    existingSecret: "freshrss-db-credentials"
    userPasswordKey: "password"
  hostname: "production-postgresql-rw.postgresql-system.svc.cluster.local"
  port: 5432

postgresql:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
