apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/component: admin-ui
    app.kubernetes.io/part-of: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/component: admin-ui
        app.kubernetes.io/part-of: postgresql
    spec:
      securityContext:
        fsGroup: 5050
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "jconlon@verticon.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_PASSWORD
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
            - name: pgadmin-servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data
        - name: pgadmin-servers
          configMap:
            name: pgadmin-servers
