apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: kafka-system
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/component: schema-registry
    app.kubernetes.io/part-of: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: schema-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schema-registry
        app.kubernetes.io/component: schema-registry
        app.kubernetes.io/part-of: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.kafka-system.svc.cluster.local:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
