apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka-system
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/component: schema-registry
    app.kubernetes.io/part-of: kafka
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.214"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: schema-registry
